DUMMY_MODERNIZATION_SECTIONS = {
    "1. EXECUTIVE SUMMARY": "This modernization strategy document outlines the transformation of a legacy system into a cloud-native architecture. The initiative focuses on improving scalability, maintainability, and operational efficiency through strategic adoption of modern technologies and architectural patterns.\n\n**Key Objectives:**\n- Migrate monolithic architecture to microservices\n- Adopt containerization with Docker and Kubernetes\n- Implement CI/CD automation pipelines\n- Improve system observability and monitoring\n- Reduce technical debt and maintenance costs",
    "2. CURRENT STATE (AS-IS)": "**Architecture Overview:**\nThe current system is a monolithic application built with legacy technologies:\n- Monolithic Java application deployed on traditional servers\n- Tightly coupled business logic and presentation layers\n- Manual deployment and scaling processes\n- Limited monitoring and observability\n- RDBMS data storage without caching layer\n\n**Technology Stack:**\n- Java 8 with Spring Framework 4.x\n- Oracle Database\n- Manual log aggregation\n- Ad-hoc monitoring through server dashboards\n\n**Pain Points:**\n- Long deployment cycles (weeks)\n- Difficult to scale individual components\n- High operational overhead\n- Limited ability to use polyglot architectures\n- Slow incident response and debugging",
    "3. MODERNIZATION STRATEGY (7Rs)": "**Strategy Classification:**\n- **Rehost (Lift & Shift):** 30% of workloads → Cloud VM instances\n- **Replatform:** 40% of workloads → Managed container services (AKS/ECS)\n- **Refactor/Re-architect:** 20% of workloads → Microservices with serverless functions\n- **Repurchase:** 5% of workloads → SaaS solutions\n- **Retire:** 5% of non-critical legacy components\n\n**Phase 1: Foundation (Months 1-3)**\n- Set up cloud infrastructure and networking\n- Establish CI/CD pipeline templates\n- Containerize core applications\n\n**Phase 2: Migration (Months 4-9)**\n- Migrate data warehouse and analytics\n- Implement microservices for new components\n- Deploy message queues for async processing\n\n**Phase 3: Optimization (Months 10-12)**\n- Performance tuning and cost optimization\n- Advanced monitoring and alerting\n- Disaster recovery implementation",
    "4. TARGET ARCHITECTURE (TO-BE)": "**Cloud-Native Architecture:**\n- **Compute:** Kubernetes clusters (AKS) with auto-scaling\n- **Data:** Azure SQL Database, Cosmos DB, Azure Data Lake\n- **Messaging:** Azure Service Bus, Event Grid\n- **API Management:** Azure API Management for gateway\n- **Identity:** Azure AD for authentication and authorization\n- **Monitoring:** Application Insights, Log Analytics, Prometheus\n\n**Microservices Breakdown:**\n1. User Service (authentication, profile management)\n2. Order Service (order processing, fulfillment)\n3. Payment Service (payment processing, reconciliation)\n4. Notification Service (email, SMS, push notifications)\n5. Analytics Service (data aggregation, reporting)\n\n**Data Flow:**\n- Event-driven communication between services\n- Asynchronous processing via message queues\n- Eventual consistency for distributed data\n- API gateway for external integrations",
    "5. DATA MODERNIZATION": "**Database Strategy:**\n- Azure SQL Database for transactional data (OLTP)\n- Cosmos DB for NoSQL requirements (user preferences, session data)\n- Azure Data Lake for analytics and big data processing\n\n**Migration Approach:**\n1. Schema mapping and validation\n2. Data validation and reconciliation\n3. Parallel run period (old and new systems)\n4. Cutover with minimal downtime\n\n**Data Governance:**\n- Implement data classification and tagging\n- Enable row-level security and encryption\n- Establish data retention policies\n- Audit logging for compliance",
    "6. MIGRATION ROADMAP": "**Timeline: 12 Months**\n\n**Q1 (Months 1-3): Preparation**\n- Week 1-2: Assessment and planning\n- Week 3-4: Infrastructure provisioning\n- Week 5-8: CI/CD pipeline setup\n- Week 9-12: Team training and knowledge transfer\n\n**Q2 (Months 4-6): Initial Migration**\n- Migrate non-critical applications\n- Implement monitoring and logging\n- Establish operational procedures\n\n**Q3 (Months 7-9): Core System Migration**\n- Migrate order processing system\n- Implement new payment service\n- Data synchronization validation\n\n**Q4 (Months 10-12): Optimization**\n- Performance tuning\n- Cost optimization\n- Production hardening\n- Go-live and cutover",
    "7. RISKS & MITIGATION": "| Risk | Likelihood | Impact | Mitigation |\n|------|-----------|--------|------------|\n| Data loss during migration | Medium | Critical | Comprehensive backup strategy, parallel run validation |\n| Performance degradation | Medium | High | Load testing, caching layer, database optimization |\n| Team skill gaps | High | High | Training programs, vendor support, gradual transition |\n| Budget overrun | Medium | High | Cloud cost management tools, staged rollout |\n| Integration issues | Medium | Medium | Extensive testing, contract testing, API contracts |\n| Vendor lock-in | Low | Medium | Use managed services with export capabilities |\n| Compliance violations | Low | Critical | Audit logging, encryption, compliance validation |\n\n**Contingency Plans:**\n- Rollback procedures for each phase\n- 24/7 support during cutover window\n- Redundant infrastructure during parallel run",
    "8. NEXT STEPS": "**Immediate Actions (Week 1):**\n1. Secure executive sponsorship and budget approval\n2. Establish cross-functional modernization team\n3. Schedule kickoff meeting with all stakeholders\n\n**Short-term (Month 1):**\n1. Conduct detailed application assessment\n2. Create detailed migration runbooks\n3. Set up development and staging environments\n4. Begin team training programs\n\n**Success Metrics:**\n- Deployment frequency: Daily (vs. quarterly now)\n- Lead time for changes: < 1 hour\n- Mean time to recovery: < 30 minutes\n- Cloud cost per transaction: 40% reduction\n- System uptime: 99.9% SLA"
}

DUMMY_MODERNIZATION_STREAM_EVENTS = [
    ("🔍 [Step 1/4] Analyzing current architecture...", 0.3),
    ("Found 42 components in monolithic application", 0.2),
    ("Parsing configuration files and dependencies...", 0.2),
    ("[TOOL] scan_codebase() — completed", 0.3),
    ("Analyzing technology debt and pain points...", 0.2),
    ("📊 [Step 2/4] Generating modernization strategy...", 0.3),
    ("Invoking Claude (claude-opus) for strategy generation...", 2.0),
    ("   Claude API call completed", 0.1),
    ("Generated 7Rs analysis and recommendations...", 0.2),
    ("🔧 [Step 3/4] Creating target architecture blueprint...", 0.3),
    ("Designing microservices topology...", 0.2),
    ("Mapping data migration paths...", 0.2),
    ("Building deployment roadmap (12-month plan)...", 0.3),
    ("Creating risk assessment and mitigation strategies...", 0.2),
    ("🔍 [Step 4/4] Reviewing blueprint (iteration 1)...", 0.3),
    ("Invoking Codex (gpt-5.3-codex) for blueprint review...", 1.5),
    ("   Codex API call completed", 0.1),
    ("Review score: 78/100 (Grade: B)", 0.1),
    ("Score 78/100 < 85, refining...", 0.2),
    ("🔧 Reconciling blueprint (iteration 1)...", 0.3),
    ("Invoking Claude (claude-opus) for blueprint reconciliation...", 2.0),
    ("   Claude API call completed", 0.1),
    ("Claude responded — Reconciled blueprint (85412 chars)", 0.3),
    ("🔍 Reviewing blueprint (iteration 2)...", 0.3),
    ("Invoking Codex (gpt-5.3-codex) for blueprint review...", 1.5),
    ("   Codex API call completed", 0.1),
    ("Review score: 82/100 (Grade: B)", 0.1),
    ("Score 82/100 < 85, refining...", 0.2),
    ("🔧 Reconciling blueprint (iteration 2)...", 0.3),
    ("Invoking Claude (claude-opus) for blueprint reconciliation...", 2.0),
    ("   Claude API call completed", 0.1),
    ("Claude responded — Reconciled blueprint (91247 chars)", 0.3),
    ("🔍 Reviewing blueprint (iteration 3)...", 0.3),
    ("Invoking Codex (gpt-5.3-codex) for blueprint review...", 1.5),
    ("   Codex API call completed", 0.1),
    ("Review score: 87/100 (Grade: A)", 0.1),
    ("✅ Done (score >= 85). Final score: 87/100", 0.3),
]

__all__ = ["DUMMY_MODERNIZATION_SECTIONS", "DUMMY_MODERNIZATION_STREAM_EVENTS"]
