"""add_reviewer_fields_and_approval_events

Revision ID: 65b597a92e25
Revises: f600436ed980
Create Date: 2026-05-06 15:21:31.860786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b597a92e25'
down_revision: Union[str, Sequence[str], None] = 'f600436ed980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_events',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('artifact_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('artifact_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('artifact_name', sa.Text(), nullable=False),
    sa.Column('from_status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('to_status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('submitted_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_events_artifact_id'), 'approval_events', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_approval_events_artifact_type'), 'approval_events', ['artifact_type'], unique=False)
    op.add_column('generated_epics', sa.Column('reviewed_by', sa.Text(), nullable=True))
    op.add_column('generated_epics', sa.Column('review_comment', sa.Text(), nullable=True))
    op.add_column('generated_epics', sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('generated_stories', sa.Column('reviewed_by', sa.Text(), nullable=True))
    op.add_column('generated_stories', sa.Column('review_comment', sa.Text(), nullable=True))
    op.add_column('generated_stories', sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_stories', 'reviewed_at')
    op.drop_column('generated_stories', 'review_comment')
    op.drop_column('generated_stories', 'reviewed_by')
    op.drop_column('generated_epics', 'reviewed_at')
    op.drop_column('generated_epics', 'review_comment')
    op.drop_column('generated_epics', 'reviewed_by')
    op.drop_index(op.f('ix_approval_events_artifact_type'), table_name='approval_events')
    op.drop_index(op.f('ix_approval_events_artifact_id'), table_name='approval_events')
    op.drop_table('approval_events')
    # ### end Alembic commands ###
